services:
    cachetool_cache_clearer:
        class: CacheTool\Bundle\Listener\CacheClearerListener
        arguments:
            - @cachetool.cache_clearer.collection
        tags:
            - { name: kernel.cache_clearer }
